const enc=new TextEncoder();
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function hex(bytes){return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function safeEqual(a,b){a=String(a||'').toLowerCase();b=String(b||'').toLowerCase();if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
async function hmac(k,d){const key=await crypto.subtle.importKey('raw',k,{name:'HMAC',hash:'SHA-256'},false,['sign']);return crypto.subtle.sign('HMAC',key,typeof d==='string'?enc.encode(d):d)}
async function auth(initData,token){if(!token)throw Object.assign(new Error('BOT_TOKEN secret is not configured'),{status:503});const p=new URLSearchParams(initData||''),rh=p.get('hash');if(!rh)throw Object.assign(new Error('Telegram session missing'),{status:401});p.delete('hash');const s=[...p.entries()].map(([k,v])=>`${k}=${v}`).sort((a,b)=>a.localeCompare(b)).join('\n'),sk=await hmac(enc.encode('WebAppData'),token),calc=hex(await hmac(new Uint8Array(sk),s));if(!safeEqual(calc,rh))throw Object.assign(new Error('Telegram signature check failed'),{status:401});const ad=Number(p.get('auth_date')),now=Math.floor(Date.now()/1000);if(!Number.isFinite(ad)||now-ad>86400||ad>now+300)throw Object.assign(new Error('Telegram session expired'),{status:401});let u=null;try{u=JSON.parse(p.get('user')||'null')}catch(_){}if(!u||u.id==null)throw Object.assign(new Error('Telegram user missing'),{status:401});return u}
let ready=false;
async function schema(env){if(ready)return;await env.DB.prepare(`CREATE TABLE IF NOT EXISTS social_friends(owner_id TEXT NOT NULL,friend_id TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(owner_id,friend_id))`).run();await env.DB.prepare(`CREATE INDEX IF NOT EXISTS idx_social_friends_owner ON social_friends(owner_id)`).run();ready=true}
function cleanPid(v){v=String(v||'').trim();if(v.startsWith('tg:'))v=v.slice(3);return /^\d{1,24}$/.test(v)?v:''}
async function listFriends(env,id){const r=await env.DB.prepare(`SELECT f.friend_id,p.nickname,p.class_key,p.telegram_first_name,p.telegram_username FROM social_friends f LEFT JOIN players p ON p.telegram_id=f.friend_id WHERE f.owner_id=?1 ORDER BY COALESCE(p.nickname,p.telegram_first_name,p.telegram_username,f.friend_id) COLLATE NOCASE`).bind(id).all();return (r.results||[]).map(x=>({id:'tg:'+String(x.friend_id),name:String(x.nickname||x.telegram_first_name||x.telegram_username||('ID '+x.friend_id)).slice(0,24),classKey:String(x.class_key||'').slice(0,24)}))}
export async function handleSocialRequest(request,env){const u=new URL(request.url);if(!u.pathname.startsWith('/api/social/'))return null;if(request.method!=='POST')return json({ok:false,message:'POST required'},405);try{let b={};try{b=await request.json()}catch(_){}const user=await auth(b.initData||request.headers.get('x-telegram-init-data')||'',env.BOT_TOKEN);if(!env.DB)throw Object.assign(new Error('Database unavailable'),{status:503});await schema(env);const id=String(user.id);if(u.pathname==='/api/social/list')return json({ok:true,friends:await listFriends(env,id)});if(u.pathname==='/api/social/add'){const fid=cleanPid(b.friendId||b.friendPid);if(!fid)return json({ok:false,message:'Игрок не найден.'},400);if(fid===id)return json({ok:false,message:'Себя добавить нельзя.'},409);const p=await env.DB.prepare('SELECT telegram_id FROM players WHERE telegram_id=?1').bind(fid).first();if(!p)return json({ok:false,message:'Игрок ещё не зарегистрирован на сервере.'},404);const now=Date.now();await env.DB.prepare('INSERT OR IGNORE INTO social_friends(owner_id,friend_id,created_at) VALUES(?1,?2,?3)').bind(id,fid,now).run();await env.DB.prepare('INSERT OR IGNORE INTO social_friends(owner_id,friend_id,created_at) VALUES(?1,?2,?3)').bind(fid,id,now).run();return json({ok:true,friends:await listFriends(env,id),message:'Игрок добавлен в друзья.'})}if(u.pathname==='/api/social/remove'){const fid=cleanPid(b.friendId||b.friendPid);if(!fid)return json({ok:false,message:'Игрок не найден.'},400);await env.DB.prepare('DELETE FROM social_friends WHERE (owner_id=?1 AND friend_id=?2) OR (owner_id=?2 AND friend_id=?1)').bind(id,fid).run();return json({ok:true,friends:await listFriends(env,id),message:'Игрок удалён из друзей.'})}return json({ok:false,message:'Social route not found'},404)}catch(e){console.error('PPA social',e);return json({ok:false,message:String((e&&e.message)||'Social server error')},Number(e&&e.status)||500)}}
